### ISSUE TITLE
При оценке метрик вылетает ошибка: Последовательность содержит более одного элемента.

### ISSUE THREAD

**Issue by karuzzo** [StanislavGrigoriev/EasyCNTK#1]
![image](https://user-images.githubusercontent.com/18124355/63654341-de8cf880-c781-11e9-9d16-9929b8c50f88.png)
 Вот кусок кода на который ругается прога

```
var metricsTrain = model
      .Evaluate(datasetTrain, inputDimension, device)
      .GetOneLabelClassificationMetrics();
```
Эта ошибка воспроизводима в примере MNIST данного репозитория, на последней версии библиотеки.
Я чувствую большой потенциал вашей библиотеки, скиньте пожалуйста ссылку на ее API если такой материал написан.

**Comment by StanislavGrigoriev** [comment]
Проверил, действительно **баг**. Проблема была в том, что метод не мог определить входную переменную (забыл исправить эксперимент, в версии 0.3.0 все работает).

Сейчас проблему исправил, добавил возможность явно указывать имя входного слоя сети при оценке, обучении, прогнозе. Это касается методов _Evaluate(), Fit(), FitMultiOutput(), Predict()_ (значение по умолчанию "Input"). 
Для сети имя входного слоя можно задать в конструкторе (необязательный параметр - значение по умолчанию так же "Input").

На данный момент обновил nuget пакет до версии **0.4.1** и примеры в репозитории.
Если проблема устранена - пожалуйста сообщите.

P.S. Документации к сожалению пока нет, поскольку версия не мажорная - могут быть еще изменения публичного API. Как только будет релиз версии 1.0, опубликую вики на странице репозитория. А пока большинство информации можно почерпнуть из комментариев к методам, в большинстве случаев они достаточно подробные.

**Comment by karuzzo** [comment]
Комментарии к методам отличные это факт, на них и ориентируюсь! )) Спасибо за столь быстрый ответ.
