### ISSUE TITLE
Вопрос: Как передать значения в модель и вернуть предикт класса MNIST

### ISSUE THREAD

**Issue by karuzzo** [StanislavGrigoriev/EasyCNTK#2]
Не могу понять как вернуть предикт класса. Сейчас делаю так: тренирую модель вашим примером mnist, далее подгружаю модель кодом:
`first_multi_model = Sequential<double>.LoadModel(device, fname_model_firstmulti);`
пробую использовать предикт передавая в модель массив значений без one-hot-encodind маркера кодом:
`double[] predict = first_multi_model.Predict(dataArray, device);`
при выполнении на строке получаю ошибку:
![image](https://user-images.githubusercontent.com/18124355/63784660-a6a7c180-c8f7-11e9-86b2-736e668913b4.png)

Полный код приложения можно посмотреть [здесь](https://yadi.sk/d/KHoNdgMlHDpXqQ).
Станислав, спасибо!

**Comment by StanislavGrigoriev** [comment]
Вы все делаете правильно, проблема внутри метода Predict(), сегодня выпущу обновление, устраняющее эту ошибку. Вам потребуется только обновиться и все заработает.

**Comment by karuzzo** [comment]
Хорошо, это радует! 
Отступая немного от темы, скажу свои пожелания, хотелось бы в будущем увидеть реализацию обучения с 3мя выборками: тренировочной, валидационной и тестовой. Честно признаюсь что сам я не знаю способа реализовать валидацию результата обучения вне методов вашей библиотеки, конечно я могу сохранять результаты обучения каждой эпохи и по завершению процесса обучения пробегать по ним валидационной выборкой а за тем тестовой, но что то мне подсказывает что это совсем не так работает. ))

**Comment by StanislavGrigoriev** [comment]
Не совсем понял что вы имеет ввиду под обучением с 3 выборками.
Эти выборки вообще имеют такой смысл:
1) тренировочная - это та выборка, на которой вы непосредственно обучаете модель.
2) валидационная - это та выборка, на которой вы **подбираете** оптимальные гиперпараметры для обучения. 
3) тестовая - это та выборка, на которой вы проверяете качество модели, которую вы обучили используя **оптимальные гиперпараметры**, подобранные с использованием валидационной выборки

Условно процесс подбора оптимальной скорости обучения (один из гиперпараметров) выглядит так:
1)  установили скорость обучения 0.1
2) обучили модель на тренировочной выборке с этой скоростью (0.1)
3) проверили полученную модель на валидационной выборке - получили точность 90%
4) установили скорость обучения 0.2
5) заново обучили модель на тренировочной выборке с этой скоростью (0.2)
6)  проверили полученную модель на валидационной выборке - получили точность 80%
7) приняли для себя, что **оптимально** будет обучать со скоростью 0.1, поскольку она дает большую точность, чем со скоростью 0.2

Естественно всевозможных вариантов очень много, учитывая число гиперпараметров и их возможных значений. Поэтому это больше один из подходов к обучению, который можно применить у любому алгоритму. Можно вообще обойтись без валидационной выборки. В каждом конкретном случае свой подход.

Если же вы хотите каждую эпоху видеть какая ошибка на валидационной выборке, то это можно сделать очень просто: 
1) разбиваете ваш датасет методом Split() на 2 части: **тренировочную** и проверочную
2) разбиваете проверочную методом Split() на 2 части, получится **валидационная** и **тестовая** выборки
3) дальше при обучении, в  параметре-делегате actionPerEpoch оцениваете качество текущей модели на **валидационной** выборке и выводите куда нужно

Сразу стоит отметить что это значительно замедлит скорость обучения, поскольку каждую эпоху вам нужно будет пробегаться по всем примерам валидационной выборки чтобы оценить качество модели.

**Comment by karuzzo** [comment]
Спасибо за столь развернутый ответ! Я пока плохо разобрался с нейросетями, но я стараюсь )) того материала который вы прислали мне хватит на несколько месяцев изучения, и надеюсь не раздражаю вас своим невежеством. Под тренировочной, валидационной и тестовой выборкой я имел в виду как раз то что вы написали. Заговорил о выборках так как имел дело с подобной ситуацией в ml.net(диплернинга думаю в этом фреймворке нет), в котором была реализация метода .Fit также как у вас в нескольких перегрузках, при этом качество модели some_model.Fit(trainData, validationData); во многом превосходило sаme_model(trainData); к сожалению внутреннею организацию метода я не знаю. Но обязательно попробую приметить то что вы написали.
